const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const path=require('path'),fs=require('fs');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const results=[];
for(const dark of [false,true])for(const width of [1040,520]){
const p=await browser.newPage({viewport:{width,height:900}});await p.goto('http://127.0.0.1:4176');await p.evaluate(d=>document.documentElement.setAttribute('data-mode',d?'dark':'light'),dark);
const root=p.locator('#actions [role=toolbar]'),refresh=root.getByRole('button',{name:'Refresh'}),paused=root.getByRole('button',{name:'Paused'}),saving=root.getByRole('button',{name:'Saving'}),docs=root.getByRole('link',{name:'Documentation'});
const geometry=await root.evaluate(r=>({height:r.getBoundingClientRect().height,width:r.getBoundingClientRect().width,items:[...r.children].map(e=>({name:e.getAttribute('aria-label')||e.textContent,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,radius:getComputedStyle(e).borderRadius,borderLeft:getComputedStyle(e).borderLeftWidth}))}));if(geometry.height!==36||geometry.items.some(x=>x.height!==36))throw Error('geometry');
await refresh.click();await refresh.press('Space');await refresh.press('ArrowRight');if(!await paused.evaluate(e=>e===document.activeElement))throw Error('focusable disabled');await paused.press('Space');await paused.press('Enter');await paused.press('ArrowRight');if(!await saving.evaluate(e=>e===document.activeElement))throw Error('skip disabled');await saving.press('Enter');await saving.press('ArrowRight');if(!await docs.evaluate(e=>e===document.activeElement))throw Error('link focus');await docs.press('Tab');if(!await p.locator('#vertical button').first().evaluate(e=>e===document.activeElement))throw Error('one Tab exit');await p.keyboard.press('Shift+Tab');if(!await docs.evaluate(e=>e===document.activeElement))throw Error('last focused reentry');await docs.press('ArrowRight');await p.keyboard.press('ArrowRight');await p.keyboard.press('ArrowRight');if(!await refresh.evaluate(e=>e===document.activeElement))throw Error('loop');await refresh.press('End');if(!await refresh.evaluate(e=>e===document.activeElement))throw Error('source End policy');
const vertical=p.locator('#vertical [role=toolbar]');await vertical.getByRole('button',{name:'Refresh'}).click();await p.keyboard.press('ArrowDown');if(!await vertical.getByRole('button',{name:'Paused'}).evaluate(e=>e===document.activeElement))throw Error('vertical');
const noLoop=p.locator('#no-loop [role=toolbar]');await noLoop.getByRole('button',{name:'Deploy'}).click();await p.keyboard.press('ArrowRight');if(!await noLoop.getByRole('button',{name:'Deploy'}).evaluate(e=>e===document.activeElement))throw Error('no-loop');
const disabled=p.locator('#disabled [role=toolbar]');if(await disabled.getByRole('button',{name:'Refresh'}).getAttribute('aria-disabled')!=='true')throw Error('group disabled');await disabled.getByRole('link',{name:'Documentation'}).click();if(!p.url().endsWith('#docs'))throw Error('group leaves links active');
if(await p.locator('#status').textContent()!=='2 activations')throw Error('unavailable activation escaped');await p.screenshot({path:path.join(__dirname,`${dark?'dark':'light'}-${width}.png`)});
results.push({theme:dark?'dark':'light',width,result:'PASS',geometry,actions:['pointer and Space once','disabled focus without activation','skipped disabled','loading inert','link participates','one Tab exit and reentry','loop and nonloop','End left to host','vertical Down','group disabled leaves links active']});await p.close();}
fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(results,null,2)+'\n');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
