[package]
name = "kumo-gallery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
frame-profiler = ["gpui-kit/profiler"]

[dependencies]
gpui-kit.workspace = true
gpui-kumo.workspace = true

[lints]
workspace = true

[dev-dependencies]
gpui-kit = { workspace = true, default-features = false, features = ["test-support"] }
